### ISSUE TITLE
Support for Iphone X

### ISSUE THREAD

**Issue by SirComet** [azfx/SimpleTab#11]
Would like to know if there is planned support for iPhone X in the future, since all constraints and other visuals break when building for iPhone X.
![screen shot 2017-12-05 at 7 26 58 pm](https://user-images.githubusercontent.com/22453986/33639720-4c1a73de-d9f2-11e7-9774-e73ac86a5a08.png)

PS. Thank you for this great library.

**Comment by azfx** [comment]
Hey @SirComet, Thanks for reporting the issue with iPhone X, wasn't aware it was broken :)
I do not have any immediate plans to support iPhone X, as I am tied up with other projects, though I may look into it during the holidays.
