### ISSUE TITLE
toBarItem's animation failed

### ISSUE THREAD

**Issue by nin-echo** [azfx/SimpleTab#4]
Hi,
I have a problem with this.
When I move to a bar item, its position doesn't change. Shouldn't it go downward?

**Comment by azfx** [comment]
Please explain the issue in more detail. Are you using any preset animation style, or your own custom animation ? Do you have a gist of the problem code you can share ?
Thanks - Abdul.

**Comment by nin-echo** [comment]
I ran the Sample ~ And I just changed the tab bar style in AppDelegate : 
`let style:SimpleTabBarStyle = ElegantTabBarStyle(tabBar: simpleTBC!.tabBar)`
but when i tap another tab bar item, it just stayed at its original position like this
![simulator screen shot 2017 3 21 12 29 57](https://cloud.githubusercontent.com/assets/12556474/24132736/a4c9980c-0e32-11e7-8d44-4f0508515187.png)
I found that the gif you've uploaded shows that it should change its frame~

**Comment by azfx** [comment]
Thanks for the screenshot, I understand the problem now. Looking into it.
