### ISSUE TITLE
Disable effects when selected item 

### ISSUE THREAD

**Issue by nodahikaru** [azfx/SimpleTab#5]
Hi
How I can disable tabbaritem text is hidden when it is selected?

**Comment by azfx** [comment]
You may create a new custom  SimpleTabBarStyle where the tabbaritem text alpha is not changed to 0. Refer [customizations](https://github.com/azfx/SimpleTab/blob/master/customizations.md) on how to create a custom style. If you use Elegant SimpleTabBarStyle, the code which hides the text on selection is [here](https://github.com/azfx/SimpleTab/blob/master/Pod/Classes/TabBarStyles/ElegantTabBarStyle.swift#L79)
