### ISSUE TITLE
crashes when used programatically

### ISSUE THREAD

**Issue by johndpope** [azfx/SimpleTab#6]
`
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        let mainTBC = SimpleTabBarController()
        mainTBC.tabBar = SimpleTabBar()
        mainTBC.viewTransition = PopViewTransition()
        
        let style:SimpleTabBarStyle = PopTabBarStyle(tabBar: mainTBC.tabBar)
        style.setIconColor(color: .lightGray, forState: .normal)
        style.setIconColor(color: .blue, forState: .selected)
        
        mainTBC.tabBarStyle = style
        mainTBC.viewControllers = buildNavigationControllers()
        window?.rootViewController = mainTBC
        return true
    }

    
    
    func buildNavigationControllers()->[UINavigationController]{
        

        let testVC = UIViewController()
        testVC.title = "Test"
        let testNC = UINavigationController()
        testNC.navigationBar.isTranslucent = false
        testNC.viewControllers = [networkVC]
        testNC.tabBarItem = SimpleTabBarItem(title: "Test",
                                         image: UIImage(named:"icon_favorites") ,
                                         selectedImage: UIImage(named:"icon_favorites"))
        
        
        let lastVC = UIViewController()
        lastVC.title = "Test"
        let lastNC = UINavigationController()
        lastNC.navigationBar.isTranslucent = false
        lastNC.viewControllers = [networkVC]
        lastNC.tabBarItem = SimpleTabBarItem(title: "Test",
                                         image: UIImage(named:"icon_favorites") ,
                                         selectedImage: UIImage(named:"icon_favorites"))
        
        return [testNC,lastNC]
        
    }`

<img width="1306" alt="screen shot 2017-03-28 at 1 03 27 pm" src="https://cloud.githubusercontent.com/assets/289994/24417642/38fed8f0-13b7-11e7-8a77-8bcc3f4b6068.png">

**Comment by johndpope** [comment]
if I just instantiate a vanilla UITabBarController instead - my code works fine. 

        let mainTBC = UITabBarController()
        mainTBC.viewControllers = buildNavigationControllers()
        window?.rootViewController = mainTBC

**Comment by johndpope** [comment]
yielding to RAMMotiontabbarcontroller.

**Comment by azfx** [comment]
Hey @johndpope, sorry could not get back to you earlier, been tied up with work. I looked at the issue you reported, and unfortunately fixing that may require some major refactor. The library is designed to work with storyboard at the moment. I will update the Readme to indicate that.
