### ISSUE TITLE
iconTopOffset and titleBottomOffset not working

### ISSUE THREAD

**Issue by anthonycastelli** [azfx/SimpleTab#7]
I've tried everything I can think of, including manually setting the imageInsets but that didn't affect anything. I have everything setup in a storyboard, but it shouldn't matter. The TabBar items in the storyboard are SimpletabBarItems so the iconTopOffset and titleBottomOffset should work. My goal is to center the icon a little bit more and remove the title.

**Comment by azfx** [comment]
Can you post a sample repo for me to look at ? I am not able to reproduce the issue. Thanks.
